"""PDF generation from HTML content using PyMuPDF (fitz).

Renders styled HTML to a paginated PDF with a professional footer
containing provider info, Kasa logo, timestamp, and optional signature.
"""

import base64
import logging
import tempfile
from datetime import datetime
from pathlib import Path

import fitz

logger = logging.getLogger("kasamd-sidecar")

# Page dimensions (US Letter)
PAGE_W = 612  # 8.5in in points
PAGE_H = 792  # 11in in points
MARGIN = 36  # 0.5in in points (matches web version)
FOOTER_HEIGHT = 80  # reserved space at bottom for footer

# Footer color: #99a1af (matches web version)
FOOTER_COLOR = (0.6, 0.631, 0.686)

# Path to the Kasa logo bundled with the sidecar
_LOGO_PATH = Path(__file__).parent.parent / "assets" / "kasagreen.png"

# CSS that matches the web version's wrapWithStyles()
DEFAULT_CSS = """
body {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 12pt;
    line-height: 1.25;
    color: #1f2937;
}
h1 {
    font-size: 18pt;
    font-weight: bold;
    margin: 12pt 0 9pt;
}
h2 {
    font-size: 15pt;
    font-weight: bold;
    margin: 10pt 0 8pt;
}
h3 {
    font-size: 13pt;
    font-weight: bold;
    margin: 9pt 0 6pt;
}
p {
    margin: 0 0 9pt;
}
ul, ol {
    margin: 0 0 9pt 9pt;
    padding-left: 8pt;
}
li {
    margin-bottom: 3pt;
}
strong, b {
    font-weight: bold;
}
em, i {
    font-style: italic;
}
u {
    text-decoration: underline;
}
"""


def generate_pdf(
    html: str,
    provider: dict | None = None,
    session_title: str | None = None,
) -> bytes:
    """Generate a PDF from HTML content with provider footer.

    Args:
        html: HTML string of the note body (from Lexical $generateHtmlFromNodes).
        provider: Dict with keys: firstName, lastName, providerType, signature (optional).
        session_title: Optional title rendered at the top of the first page.

    Returns:
        PDF file contents as bytes.
    """
    if not html or not html.strip():
        raise ValueError("HTML content is required")

    provider = provider or {}

    # Wrap HTML with optional title
    full_html = html
    if session_title:
        safe_title = _escape_html(session_title)
        full_html = f"<h1>{safe_title}</h1>{html}"

    # Content rect: margins on all sides, reserving space for footer at bottom
    content_rect = fitz.Rect(
        MARGIN, MARGIN, PAGE_W - MARGIN, PAGE_H - MARGIN - FOOTER_HEIGHT
    )

    # Render HTML to a temp PDF via Story + DocumentWriter
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
        tmp_path = tmp.name

    try:
        story = fitz.Story(html=full_html, user_css=DEFAULT_CSS)
        writer = fitz.DocumentWriter(tmp_path)

        while True:
            dev = writer.begin_page(fitz.Rect(0, 0, PAGE_W, PAGE_H))
            more, _ = story.place(content_rect)
            story.draw(dev)
            writer.end_page()
            if not more:
                break

        writer.close()

        # Open the rendered PDF and add footer to each page
        doc = fitz.open(tmp_path)
        _add_footers(doc, provider)
        pdf_bytes = doc.tobytes()
        doc.close()
    finally:
        Path(tmp_path).unlink(missing_ok=True)

    return pdf_bytes


def _add_footers(doc: fitz.Document, provider: dict) -> None:
    """Add footer with provider info, logo, and signature to every page."""
    footer_y = PAGE_H - MARGIN - FOOTER_HEIGHT
    now = datetime.now()
    date_str = now.strftime("%b %-d, %Y")
    time_str = now.strftime("%-I:%M %p")
    timestamp = f"{date_str} {time_str}"

    first_name = provider.get("firstName") or ""
    last_name = provider.get("lastName") or ""
    provider_type = provider.get("providerType") or ""
    signature_data = provider.get("signature")

    # Build provider name with fallback
    if first_name or last_name:
        provider_name = f"{first_name} {last_name}".strip()
    else:
        provider_name = "Provider"

    provider_label = provider_name
    if provider_type:
        provider_label = f"{provider_name}, {provider_type}"

    # Decode signature image if present
    signature_bytes = None
    if signature_data and isinstance(signature_data, str):
        signature_bytes = _decode_data_url(signature_data)

    for page in doc:
        # Horizontal rule
        page.draw_line(
            fitz.Point(MARGIN, footer_y),
            fitz.Point(PAGE_W - MARGIN, footer_y),
            color=FOOTER_COLOR,
            width=0.5,
        )

        # Left side: "Generated by [logo] • {timestamp}"
        # Text baseline is at footer_y + 18; logo is vertically centered to match
        left_x = MARGIN
        text_y = footer_y + 18
        font_size = 9

        page.insert_text(
            fitz.Point(left_x, text_y),
            "Generated by",
            fontsize=font_size,
            fontname="Helvetica",
            color=FOOTER_COLOR,
        )

        # Logo inline after "Generated by" — sized to match text height
        logo_x = left_x + fitz.get_text_length("Generated by  ", fontsize=font_size)
        logo_h = 14  # height in pts, visually balanced with 9pt text
        logo_w = 42  # wider to preserve aspect ratio of "kasa^MD" wordmark
        # Center logo vertically on the text baseline (baseline is ~70% down from top)
        logo_top = text_y - logo_h * 0.7
        if _LOGO_PATH.exists():
            logo_rect = fitz.Rect(logo_x, logo_top, logo_x + logo_w, logo_top + logo_h)
            page.insert_image(logo_rect, filename=str(_LOGO_PATH))
            after_logo_x = logo_x + logo_w + 6
        else:
            after_logo_x = logo_x

        page.insert_text(
            fitz.Point(after_logo_x, text_y),
            f"\u2022  {timestamp}",
            fontsize=font_size,
            fontname="Helvetica",
            color=FOOTER_COLOR,
        )

        # Right side: "Electronically signed by" + provider name
        signed_text = "Electronically signed by"
        signed_w = fitz.get_text_length(signed_text, fontsize=9)
        page.insert_text(
            fitz.Point(PAGE_W - MARGIN - signed_w, footer_y + 14),
            signed_text,
            fontsize=9,
            fontname="Helvetica",
            color=FOOTER_COLOR,
        )

        label_w = fitz.get_text_length(
            provider_label, fontsize=9, fontname="Helvetica-Bold"
        )
        page.insert_text(
            fitz.Point(PAGE_W - MARGIN - label_w, footer_y + 26),
            provider_label,
            fontsize=9,
            fontname="Helvetica-Bold",
            color=FOOTER_COLOR,
        )

        # Signature image (if available) — below provider name, right-aligned
        if signature_bytes:
            try:
                sig_max_w = 100
                sig_max_h = 35
                sig_x = PAGE_W - MARGIN - sig_max_w
                sig_y = footer_y + 32
                sig_rect = fitz.Rect(sig_x, sig_y, sig_x + sig_max_w, sig_y + sig_max_h)
                page.insert_image(sig_rect, stream=signature_bytes)
            except Exception:
                logger.warning("Failed to render signature image in PDF footer")


def _decode_data_url(data_url: str) -> bytes | None:
    """Decode a data URL (data:image/png;base64,...) to raw bytes."""
    try:
        if data_url.startswith("data:"):
            # Strip "data:image/...;base64," prefix
            _, encoded = data_url.split(",", 1)
            return base64.b64decode(encoded)
        else:
            # Might be raw base64 without prefix
            return base64.b64decode(data_url)
    except Exception:
        logger.warning("Failed to decode signature data URL")
        return None


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
