"""Tests for the PDF generation module."""

import base64

import fitz
import pytest

from sidecar.src.pdf_generator import generate_pdf


class TestBasicPdfGeneration:
    """Tests for basic PDF creation from HTML."""

    def test_generates_valid_pdf(self):
        html = "<p>Hello, world!</p>"
        result = generate_pdf(html)
        assert isinstance(result, bytes)
        assert len(result) > 0
        # Verify it's a valid PDF by opening with fitz
        doc = fitz.open(stream=result, filetype="pdf")
        assert len(doc) >= 1
        doc.close()

    def test_contains_text_content(self):
        html = "<p>Patient presents with headache.</p>"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Patient presents with headache" in text
        doc.close()

    def test_renders_bold_text(self):
        html = "<p>This is <strong>important</strong> text.</p>"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "important" in text
        doc.close()

    def test_renders_headings(self):
        html = "<h1>Title</h1><h2>Section</h2><p>Body text.</p>"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Title" in text
        assert "Section" in text
        assert "Body text" in text
        doc.close()

    def test_renders_lists(self):
        html = "<ul><li>Item one</li><li>Item two</li></ul>"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Item one" in text
        assert "Item two" in text
        doc.close()

    def test_renders_session_title(self):
        html = "<p>Note body.</p>"
        result = generate_pdf(html, session_title="Follow-up Visit")
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Follow-up Visit" in text
        doc.close()

    def test_session_title_escapes_html(self):
        html = "<p>Body.</p>"
        result = generate_pdf(html, session_title="<script>alert('xss')</script>")
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        # Title should be rendered as text, not interpreted as HTML.
        # The escaped entities show as literal angle brackets in the PDF text.
        assert "Body" in text
        # Verify it generated a valid PDF (the escaping prevented HTML injection)
        assert len(doc) >= 1
        doc.close()


class TestFooter:
    """Tests for provider footer rendering."""

    def test_footer_shows_provider_name(self):
        html = "<p>Note content.</p>"
        provider = {"firstName": "Jane", "lastName": "Doe", "providerType": "MD"}
        result = generate_pdf(html, provider=provider)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Jane Doe, MD" in text
        doc.close()

    def test_footer_shows_generated_by(self):
        html = "<p>Note content.</p>"
        result = generate_pdf(html, provider={})
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Generated by" in text
        doc.close()

    def test_footer_shows_electronically_signed(self):
        html = "<p>Note content.</p>"
        result = generate_pdf(html, provider={"firstName": "John", "lastName": "Smith"})
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Electronically signed by" in text
        doc.close()

    def test_footer_fallback_provider_name(self):
        html = "<p>Note content.</p>"
        result = generate_pdf(html, provider={})
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "Provider" in text
        doc.close()

    def test_footer_with_signature(self):
        """Test that a base64 signature image doesn't crash PDF generation."""
        html = "<p>Note content.</p>"
        # Create a tiny valid PNG for testing
        tiny_doc = fitz.open()
        tiny_page = tiny_doc.new_page(width=100, height=40)
        tiny_page.insert_text(fitz.Point(10, 25), "Sig", fontsize=14)
        tiny_bytes = tiny_doc.tobytes()
        tiny_doc.close()
        # We need an actual image, not a PDF — create a 1x1 PNG via pixmap
        pix = fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, 50, 20), 1)
        pix.clear_with(255)  # white
        sig_bytes = pix.tobytes("png")
        sig_b64 = base64.b64encode(sig_bytes).decode()
        sig_data_url = f"data:image/png;base64,{sig_b64}"

        provider = {
            "firstName": "Jane",
            "lastName": "Doe",
            "providerType": "DO",
            "signature": sig_data_url,
        }
        result = generate_pdf(html, provider=provider)
        doc = fitz.open(stream=result, filetype="pdf")
        assert len(doc) >= 1
        # Check images are present on the page (logo + signature)
        images = doc[0].get_images()
        assert len(images) >= 1  # at least the signature
        doc.close()

    def test_footer_with_null_signature(self):
        """Null signature should not crash."""
        html = "<p>Note content.</p>"
        provider = {"firstName": "John", "lastName": "Doe", "signature": None}
        result = generate_pdf(html, provider=provider)
        assert isinstance(result, bytes)
        assert len(result) > 0


class TestEdgeCases:
    """Tests for edge cases and error handling."""

    def test_empty_html_raises(self):
        with pytest.raises(ValueError, match="HTML content is required"):
            generate_pdf("")

    def test_whitespace_html_raises(self):
        with pytest.raises(ValueError, match="HTML content is required"):
            generate_pdf("   \n  ")

    def test_none_provider(self):
        """None provider should use defaults."""
        html = "<p>Content.</p>"
        result = generate_pdf(html, provider=None)
        assert isinstance(result, bytes)

    def test_multipage_note(self):
        """Long content should span multiple pages."""
        paragraphs = "".join(f"<p>Paragraph {i}. " + "x " * 100 + "</p>" for i in range(50))
        html = f"<h1>Long Note</h1>{paragraphs}"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        assert len(doc) > 1, "Expected multi-page PDF"
        # Footer should be on every page
        for page in doc:
            text = page.get_text()
            assert "Generated by" in text
        doc.close()

    def test_mixed_formatting(self):
        """HTML with mixed inline formatting."""
        html = "<p>The patient has <strong>severe</strong> <em>chronic</em> pain.</p>"
        result = generate_pdf(html)
        doc = fitz.open(stream=result, filetype="pdf")
        text = doc[0].get_text()
        assert "severe" in text
        assert "chronic" in text
        assert "pain" in text
        doc.close()
